### ISSUE TITLE
Access model params (and tree info) without serializing model

### ISSUE THREAD

**Issue by bschreck** [catboost/catboost#1082]
Problem: There is no way to access basic information about the model without first serializing to disk (which is slow). For instance, SHAP saves catboost models to json and immediately loads the json just to access information about trees like the leaf weights: https://github.com/slundberg/shap/blob/master/shap/explainers/tree.py#L1340

catboost version: master
Operating System: linux + macos
CPU:
# GPU:

**Comment by annaveronika** [comment]
You don't have to save the model to disc in order to calculate shap values.
You can call get_feature_importance method to do it:
https://catboost.ai/docs/concepts/python-reference_catboost_get_feature_importance.html

Here is a tutorial which shows how to call this method and use visualisation from shap library:
https://github.com/catboost/tutorials/blob/master/classification/classification_tutorial.ipynb
Look on In [51]: and further.

Also I'm not sure that the shap library TreeExplainer uses saving to json, this code is for something else. TreeExplainer in shap library uses get_feature_importance method for shap values calculation.

**Comment by annaveronika** [comment]
If you want to access model params, you need get_params() or get_all_params() method.
If you want to look on the trees, then you need to use tree visualization or indeed saving to json.

**Comment by annaveronika** [comment]
So the question is, what exactly do you want to do and are not able to do?

**Comment by bschreck** [comment]
Ah yeah actually looking into it more we don't need the TreeExplainer. However- in general this class should be able to function without saving and reloading a catboost model to disk. It's incredibly slow. Why not just make these tree params visible with get_all_params()?

**Comment by annaveronika** [comment]
First of all, I'm not sure saving the model on disk is the bottleneck in your case.
Secondly, get_all_params() returns training parameters, not tree structures, so it's not the right place for tree structures.
Anyway, tree structures in catboost are kind of complex, because they are using numerical features that are based on categorical feature combinations, and to calculate such numerical feature you need a hash table near the tree. So it's not an obvious class with a set of splits, and it's not clear, how to represent it to be useful. We tried our best in json model, so you need to use it if you are want to look on the tree structures.

**Comment by annaveronika** [comment]
I hope, it helped! Let us know, if you have more questions.
