### ISSUE TITLE
Interaction Feature Importance - Empty

### ISSUE THREAD

**Issue by BrianMiner** [catboost/catboost#115]
Using version '0.2.2'

Using the toy example, returns an empty interaction FI. Is the usage here incorrect?

from catboost import CatBoostClassifier

# Initialize data
cat_features = [0,1,2]
train_data = [["a","b",1,4,5,6],["a","b",4,5,6,7],["c","d",30,40,50,60]]
train_labels = [1,1,-1]
test_data = [["a","b",2,4,6,8],["a","d",1,4,50,60]]
# Initialize CatBoostClassifier
model = CatBoostClassifier(iterations=2, learning_rate=1, depth=2, loss_function='Logloss')
# Fit model
model.fit(train_data, train_labels, cat_features)

model.get_feature_importance(X=train_data,y=train_labels,cat_features=cat_features,fstr_type='Interaction')

returns

[]

**Comment by nikitxskv** [comment]
@BrianMiner Hello!
Thank you for report!

To ensure that the list is not empty, it is necessary that at least one tree should use at least two different features in the splits.
In your case, due to the fact that the dataset is too small, both trees have a depth of 1 and the algorithm can not calculate the feature interaction.

Try to increase the dataset and the number of iterations.

We will also add to our documentation that the pairs that are not listed in the result have 0 interaction.
