### ISSUE TITLE
Is it possible to encode the dataset and output for other models?

### ISSUE THREAD

**Issue by herbzhao** [catboost/catboost#1168]
Hi,
Maybe I was using the wrong search terms. But is it possible to use catboost's nice cat encoders to pre-process the data and compare catboost with other models later on?

Basically using Catboost encoders separately.

Yours

**Comment by annaveronika** [comment]
Sorry for a long response! It is not possible to extract the categorical feature encodings, because of two reasons:
- in catboost we train several models simultaneously, and for every model new numerical features are calculated on a different permutation
- features for combinations are gerenated in a greedy way during training, so it is not possible to calculate them in advance

Hope it helps!
