### ISSUE TITLE
Normalisation on regressor

### ISSUE THREAD

**Issue by laopisai** [catboost/catboost#1172]
Is it possible to do normalisation on regression problem?
Will it be possible then to configure regressor to use softmax as output.

We are thinking whether or not we can leverage softmax to put a range limit on the regression output.
Some scenario requires that a regression output never goes over a min  and max value

**Comment by annaveronika** [comment]
It is possible to normalize the formula, to do that you can use set_scale_and_bias function of CatBoostRegressor class.
It is not possible to configure regressor to use softmax as output, if you want probabilities, you need to use CatBoostClassifier.

But I'm not sure you need any of these, because after normalization your predictions will be normalized, so RMSE will be different. Easiest thing you could do is if you get a value larger than maximum, then use the maximum instead. But this is not an issue for catboost, it's more an open question. I would recommend posting it on stackoverflow for example.

**Comment by annaveronika** [comment]
I hope I answered your question. Thanks for using the library, hope you find the solution!
