### ISSUE TITLE
Question about init_model

### ISSUE THREAD

**Issue by Victor127207** [catboost/catboost#1176]
Problem: 
Hi to everybody,
I would like to know how exactly works the parameter init_model when I continue to train a model. Could you make a basic example? In particular I want to use it to continue to train a model, chosen using a dataset, with another dataset and I want to know if it takes into account old data or not. 
Thank you very much.

catboost version:
Operating System:
CPU:

**Comment by andrey-khropov** [comment]
> I would like to know how exactly works the parameter init_model when I continue to train a model.

What do you mean by "how exactly works"? Are you interested in algorithm details or how to use `init_model` functionality?

> Could you make a basic example?

There are examples in the documentation [here](https://catboost.ai/docs/concepts/python-usages-examples.html#training-continuation)

> In particular I want to use it to continue to train a model, chosen using a dataset, 

What do you mean by "chosen using a dataset"? Do you mean this dataset was used as a training dataset?

> with another dataset 

Yes, it is possible, just pass a different dataset to the `fit` function. But it is necessary that this dataset must be compatible by features with the `init_model`, all the features from the first dataset must be present in the second dataset: either be in the same sequential order or both the first and the second datasets must have feature names and the second dataset's features must be a superset of the first dataset's features in any order (if names are present, features are matched by names, not by their sequential order). New features can be present in the second dataset (although adding new features has been broken since release 0.20, I am working on the fix in #1196).

Here is a basic example (without adding new features):

```py
from catboost import CatBoostRegressor

# initial training

train_data_1 = [
    [1, 4, 5, 6],
    [4, 5, 6, 7],
    [30, 40, 50, 60]
]

train_labels_1 = [10, 20, 30]

model1 = CatBoostRegressor()

model1.fit(train_data_1, train_labels_1)

# continue training with a different dataset

train_data_2 = [
    [8, 9, 10, 11],
    [70, 80, 90, 100]
]

train_labels_2 = [40, 50]

model2 = CatBoostRegressor()

model2.fit(train_data_2, train_labels_2,  init_model=model1)
``` 

> and I want to know if it takes into account old data or not.

Training continuation means new decision trees are added to the model. The first trees are taken as is from the `init_model` so old data is not used explicitly.

**Comment by Eve-Chen** [comment]
Follow up question. Suppose we have 
```
model1 = CatBoostRegressor(iterations=2)
model1.fit(train_data_1, train_labels_1)
```
If we continue training with:
```
model2 = CatBoostRegressor(iterations=4)
model2.fit(train_data_1, train_labels_1, init_model=model1)
```
Would model2 incrementally train 2 or 4 estimators? What's the role of init_model here?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
model2 includes model1 (two estimators) plus another two estimators.

**Comment by George713** [comment]
> model2 includes model1 (two estimators) plus another two estimators.

This would mean, that the usage of `init_model` makes only sense, when the new model has more estimators than the last model? Is that correct?

**Comment by papart** [comment]
> Follow up question. Suppose we have
> 
> ```
> model1 = CatBoostRegressor(iterations=2)
> model1.fit(train_data_1, train_labels_1)
> ```
> 
> If we continue training with:
> 
> ```
> model2 = CatBoostRegressor(iterations=4)
> model2.fit(train_data_1, train_labels_1, init_model=model1)
> ```
> 
> Would model2 incrementally train 2 or 4 estimators? What's the role of init_model here?

I tested that on catboost v1.0.3.
`model2` would take 2 existing estimators of `model1` and train 4 more on top of them. As a result, `model2` would have 6 estimators in total. One can check that, for example, by using `model2._object._get_tree_count()` (returns 6) or `model2.get_tree_leaf_counts()` (returns a list with 6 values). 
Note that `model2.get_params()['iterations']` is still 4 because this value was given at initialization of `model2`.
