### ISSUE TITLE
Source releases on Github and PyPi

### ISSUE THREAD

**Issue by synapticarbors** [catboost/catboost#12]
It would be helpful to put source releases on pypi (instead of just wheels) as well as using the formal Github release archive. I'm interested in this if we want to build a package for conda-forge. See:

https://conda-forge.org/docs/meta.html#build-from-tarballs-not-repos

**Comment by Donskov7** [comment]
Yeah, it's good advice! We'll do it soon.

**Comment by exprmntr** [comment]
Actually we have no plans to provide source releases now.

**Comment by andrey-khropov** [comment]
Source releases are are available on PyPI since CatBoost 1.2. See #830. 
GitHub releases also contain the full source code in archives (although these archives of the whole repository are much heavier at approx 500Mb for tar.gz vs ~70Mb for python-specific source tar.gz archive on PyPI).

Documentation on how to build python packages from source has also been updated - https://catboost.ai/en/docs/installation/python-installation-method-build-from-source
