### ISSUE TITLE
CB_THREAD_LIMIT

### ISSUE THREAD

**Issue by TarasDerevianko** [catboost/catboost#120]
catboost/catboost/libs/algo/params.h

By default, we have the maximum number of cores 32.  (constexpr int CB_THREAD_LIMIT = 32;)

What is it related to? 

Can you change this parameter to 100 and recompile the library for easy installation in anaconda3?

**Comment by annaveronika** [comment]
This is because we want training to return deterministic results independent from amount of threads that are used. To do that we parallelize calculation into CB_THREAD_LIMIT tasks which are executed by one or more (up to CB_THREAD_LIMIT) threads. If you need a larger value you need to recompile the library.

**Comment by annaveronika** [comment]
We'll update the limit to 52 in the next version.
