### ISSUE TITLE
Exception computing SHAP values

### ISSUE THREAD

**Issue by ecoskian** [catboost/catboost#1231]
Problem: Exception computing SHAP values
catboost version: 0.22
Operating System: macOS 10.15.2
CPU: Intel Core i9
# GPU: 1

Getting the following exception computing SHAP values when training a CatBoostClassifier with default parameters other than monotone_constraints and some categorical_features. Removing the monotone_constraints results in no issues with SHAP.

CatBoostError: catboost/libs/fstr/shap_values.cpp:810: Cannot calc shap values, model contains non zero approx for zero-weight leaf

**Comment by ek-ak** [comment]
Hello! Sorry for the long time response. Could you provide a minimal reproducing example of your problem or your model parameters?

**Comment by pplonski** [comment]
Here is code to reproduce https://github.com/catboost/catboost/issues/1216

**Comment by annaveronika** [comment]
We are working on the fix now, it'll be out in the next minor release.

**Comment by ek-ak** [comment]
Hello and sorry for long time no answer! The code example from  https://github.com/catboost/catboost/issues/1216 reproduces the bug in shap calculaction for models with ranking objectives, Quantile or  MAE loss_functions. The fix is in code now and will be out in the next minor release. For now you could build from source to overcome the problem. Thanks again for reporting it!

**Comment by annaveronika** [comment]
You can build from source now or wait for the next minor release.
