### ISSUE TITLE
Flat buf models

### ISSUE THREAD

**Issue by vJenny** [catboost/catboost#124]
After training using GPU-version I've got a model in format **.bin**. Is it possible to use this model in Python-version? Or the only allowed format for ```load_model``` is **.cbm**? 
When I try to load .bin model, I get this error:  
  
*CatboostError: util/ysaveload.h:55: can not load pod type(8, 0 bytes)*

Python 3.5.2
CatBoost 0.2.2

**Comment by annaveronika** [comment]
The problem is that we made some changes to our binary representation of model. To make it work you need to build the python package from source from the same revision that you have built the GPU training.

We are very sorry for this inconvenience, we are currently changing our model to flat buffer format so that there will be no more breaking changes, it'll be updated very soon.

**Comment by kizill** [comment]
We released flatbuffer model format in v0.4.
