### ISSUE TITLE
Ya script sources

### ISSUE THREAD

**Issue by podshumok** [catboost/catboost#131]
Somewhat related to #34 and #128 

Please provide ya script sources
or consider migration to other build system like CMake
or publish generated makefiles for popular platforms
or provide explanation of what ya binary does so migration code could be contributed

Thank you!

**Comment by daskol** [comment]
@podshumok Well, [this comment](https://github.com/catboost/catboost/issues/34#issuecomment-316491894) in #34 completely answer your request. Briefly, it will be done later.

**Comment by podshumok** [comment]
Yeah, but it was like three months ago and I thought there should be an open issue about it

**Comment by sab** [comment]
From 0.6.3 it’s possible to build command-line CPU version of CatBoost under Linux with make file. See documentation https://tech.yandex.com/catboost/doc/dg/concepts/cli-installation-docpage/#make-install

**Comment by daskol** [comment]
@sab Is this makefile generated with CMake or AutoTools or somethin else? Otherwise that makefile is useless in general.

**Comment by exprmntr** [comment]
It is generated with "ya make --makefile"

**Comment by sab** [comment]
@daskol 
> Otherwise that makefile is useless in general.

Why?

**Comment by daskol** [comment]
@exprmntr I mean there are no sources for makefile generation like CMake `CMakeLists.txt`, or autoconf `configure` script, or event something like Bazel `BUILD`. Instead of that tons of python code should be used to download 200M bunch of stuff in order to generate makefile in order to build CatBoost.

Moreover, there is no large community and documentation around `ya make` but there is `ymake` binary. In addition it looks like `ymake` draw its own dependency on `scipy`.

```bash
$ ./ya make --makefile
Downloading https://storage.mds.yandex.net/get-devtools-opensource/471749/8ae6d2cac15c8cb593cf164d728c74cc [..] OK
Downloading https://storage.mds.yandex.net/get-devtools-opensource/471749/506742032 [...........................] OK
Info: will fetch 'YMake' from sandbox
Error[-WBadFile]: in $S/contrib/python/scipy-0.18.1/scipy/stats/ya.make: cannot find source file: statlibmodule.c
Error[-WUserErr]: in $S/build/cuda/ya.make: No CUDA Toolkit for your build
Configure error (use -k to proceed)
```

@sab Well, I can build CatBoost with that makefile or with `ya make` as before. In this sense assembling with makefile does not bring any benefits. In my opinion there is few common requirements to project assembling which are very convinient for distribution and packaging. 

1. Modularity. Limited number of components and scripts which define assembling.
2. Transitive building of project dependencies like `catboost` depends on `scipy`.  If one builds `catboost` then `scipy` will be built too.
3. Public target export. This provides ability to use `catboost` as build dependency of Wunderwaffe project.
4. Transparent way to pass options to build script and to modify of build script.

Rock-solid makefile does not satisfy any point of the list but still I can build CatBoost with `make` now. That's great.

**Comment by annaveronika** [comment]
We provided make files and decided to not provide sources of ya, because open-sourcing ya make is a very large task for us and it's low priority. Please use make files if you don't want to use ya.

**Comment by andrey-khropov** [comment]
1) CatBoost has switched to CMake-based build since https://github.com/catboost/catboost/commit/c5c642ca0b8e093336d0229ac4b14c78db3915bb. See https://catboost.ai/en/docs/concepts/build-from-source

2) Ya tool has been recently made open-source as well: https://github.com/yandex/yatool
