### ISSUE TITLE
Time trend and seasonality

### ISSUE THREAD

**Issue by ludovicgauvin** [catboost/catboost#1354]
Hi,

I know that usually regression trees are not able to manage time trend but that one needs to change a feature in order to take into account seasonality (https://github.com/catboost/catboost/issues/613).

Usually I stationnarize my data by regressing it on a trend (TS data) of applying first difference (DS data) before using it in a model.

I would like to know if catboost is able to manage time trend if I do not stationnarize the data first ? Even if it manages it during the training part, when I want to forecast future points, I have the feeling that it would take the max of timestamp found in the training set.

@david-waterworth you seem to know how to manage time series with catboost, any help or advice would be welcome.

Have a good day,
Ludo

**Comment by david-waterworth** [comment]
@ludovicgauvin you're correct, if you use time as a feature then the predictions for test samples after the maximum will fall in the same leaf and hence will result in the same prediction (all other features being the same). Generally, I encode time as sin/cos terms at various frequencies based on the cycles in the underlying data (hour of day, day of week and month of year in the case of energy prediction) which handles the seasonality well (provided you train with multiples of the longest cycle otherwise you may overfit) but in order to handle trend I remove it prior as you mention.

**Comment by LyzhinIvan** [comment]
I think, @david-waterworth fully answered your question. So I close the issue.
