### ISSUE TITLE
grid_search with early stopping is not using number of iterations of best model

### ISSUE THREAD

**Issue by savamirkovic** [catboost/catboost#1423]
Hi team,

I used CatBoost's grid_search for CatBoostClassifier (iterations=1000). When I use early_stopping in the CatBoostClassifier, I notice that the training is really stopped when the conditions stated by the early_stopping are met, i.e. not going to full number of iterations. 

However, since grid_search does perform fit with best obtained parameters, I noticed that the number of iterations for the best model is still 1000. How is this possible, since I used early_stopping in the first place?

catboost version:  0.24
Operating System: Ubuntu 18.04
CPU: Intel(R) Core(TM) i7-6600U CPU @2.60GHz

**Comment by kizill** [comment]
Hello and sorry for late answer.
It's expected behaviour - we can't change iterations count looking only on final tree count in model, as iterations count setting directly affects some training parts. For example, initial iterations count is a part of random_strength coefficient calculation per tree.
