### ISSUE TITLE
Custom RMSE loss function

### ISSUE THREAD

**Issue by armanhak** [catboost/catboost#1519]
Problem: Custom loss function
catboost version: 0.24.2

Could you please tell me how the derivatives were calculated for RMSE, which are indicated on the site [https://catboost.ai/docs/concepts/python-usages-examples.html#custom-objective-function](https://catboost.ai/docs/concepts/python-usages-examples.html#custom-objective-function) , an example for custom loss functions? As I understand it, these are derivatives for MSE?

The site provides the following code:

```
class RmseObjective(object):
    def calc_ders_range(self, approxes, targets, weights):
        assert len(approxes) == len(targets)
        if weights is not None:
            assert len(weights) == len(approxes)
        
        result = []
        for index in range(len(targets)):
            der1 = targets[index] - approxes[index]
            der2 = -1

            if weights is not None:
                der1 *= weights[index]
                der2 *= weights[index]

            result.append((der1, der2))
        return result
```

For RMSE, I calculate the following derivatives:

```
der1 = (approxes[index] - targets[index])/np.sqrt((targets[index]- approxes[index])**2)
der2 = 0
```

 but the model is not trained.

**Comment by kizill** [comment]
Yes, we are calculating MSE derivatives, because RMSE is metric name and we are optimizing MSE. 
Derivatives are calculated per-object, so when you are calculating pointwise RMSE loss, you are actually calculating MAE loss (square root of squared value of (target - approx) equals absolute value (target - approx)). And of course der1 equals to sign(approx - target) and der2 == 0. It's just another loss function you are dealing with :)
If there are any questions, feel free to reopen.

**Comment by armanhak** [comment]
@kizill Thanks for your reply. It is not entirely clear why the second derivative is needed, please explain.
For my task, I want to minimize the following loss function ((target - approx) ** 2) / target. Do I understand correctly that 
der1 = - (approx - target) / target, and
der2 = -1 / (target)

**Comment by LyzhinIvan** [comment]
Hi, @armanhak!

> It is not entirely clear why the second derivative is needed, please explain.
CatBoost has several leaves estimation methods (Exact, Gradient, Newton). For custom loss functions CatBoost uses Newton method by default, so it requires second derivatives. But you can set leaf estimation method to Gradient, then second derivatives will not be used. Exact is available only for few loss functions (MAE, MAPE, Quantile). 

> For my task, I want to minimize the following loss function ((target - approx) ** 2) / target. Do I understand correctly that
> der1 = - (approx - target) / target, and
> der2 = -1 / (target)
Yes, you are correct.

**Comment by Serebryanskiy** [comment]
This is very confusing. "we are calculating MSE derivatives, because RMSE is metric name and we are optimizing MSE." The name of the function is RMSE objective means you should optimize sqrt( (y_pred - y_true) ** 2), which is for pointwise case indeed MAE. The name should be MSEObjective to avoid confusion.
