### ISSUE TITLE
No possibility to output Auxiliary columns when inferencing using Command Line version

### ISSUE THREAD

**Issue by dmitryungurean** [catboost/catboost#1659]
Problem: No possibility to output Auxiliary columns when inferencing using Command Line version
catboost version: 0.25.1 linux command line

Dear Catboost Team,

I've noticed that somewhere between versions 24.4 and 25.1 the option --output-columns started to behave totally different. Since version 25.1 I am not able to output the unique ID column (that is present in the inferencing dataset and is described as Auxiliary in column description file). Until version 24.4 there were no issues, I was able to include any Auxiliary variable in the output file.

Folks in Catboost's Telegram Group confirmed that it is not possible to output Auxiliary columns anymore:( 

It was very handy to have unique IDs for each case for the inferencing. It was kind of a control tool, you didn't have to worry about changes in rows order, row duplicates or skips for some reasons.

Would it be possible to get this feature back in the future releases?

Thanks a lot in advance and keep up the extraordinary work that you are doing!!!

**Comment by andrey-khropov** [comment]
Since release 1.2.3 it is now possible to output `Auxiliary` columns again. It is now possible to specify names for `Auxiliary` columns and you can specify this name as one of the columns in the `--output-columns` option to print this column.

Example (tabs are shown as `\t` for clarity):

Dataset (assuming it has 2 features):

```
S1 \t 0.1 \t 0.11
S2 \t 0.2 \t 0.22
```

Column description file:

```
0 \t Auxiliary \t AuxId1
```

Calc call:

```
catboost calc --model-file <model_file_path> --input-path <dataset_path> --output-path <output_path> --output-columns RawFormulaVal,AuxId1 
```

will output the following to the file specified by `output_path`:

```
<Raw formula val for sample 0> \t S1
<Raw formula val for sample 1> \t S2
```

We'll update the documentation soon to reflect this as well.
