### ISSUE TITLE
ModuleNotFoundError: No module named '_catboost'

### ISSUE THREAD

**Issue by zhenlingcn** [catboost/catboost#1803]
Problem: ModuleNotFoundError: No module named '_catboost'
Catboost version: 0.26.1
Operating System: Ubuntu 20
CPU: AMD 2990WX

I intend to run a large benchmark study with respect to CatBoost. However, although this package performs well when I only run a small scale experiment, when I enlarge the experimental scale, I found it will raise this error. By the way, I have realized that my memory was completely consumed. Thus, this error might have some relationships with memory drainage. However, this package does not provide any other information to help me to solve this problem.

**Comment by kizill** [comment]
Hello! I guess that in your case it could be due to _catboost.so loading process, that may require additional memory allocations. First of all, i guess you should try to limit memory, used for training by setting `used_ram_limit` and proper worker count. Another thing that i can recommend - you can try to load catboost before forking your experimental subprocesses and you can try avoid additional data processing in each worker by using prequatization technique: look at docs 
https://catboost.ai/docs/concepts/python-reference_pool_quantized.html and https://catboost.ai/docs/concepts/python-reference_utils_quantize.html
If all this didn't work for you - please reopen and give us more information about your case :)
