### ISSUE TITLE
Add 'metric_period' param into Python wrapper

### ISSUE THREAD

**Issue by PayneJoe** [catboost/catboost#212]
After setting verbose = False, it still prints progressing messages every single step.  Parameter metric_peroid mentioned [here](https://github.com/catboost/catboost/issues/142)  not work either? How can I make it silent? Thanks,

By the way, I installed catboost with pip3.6, running on ubuntu 16.04.

**Comment by sab** [comment]
Hi PayneJoe!

'verbose' is deprecated since 0.4 (https://github.com/catboost/catboost/releases/tag/v0.4) 
It's better to use logging_level='Silent' param (https://tech.yandex.com/catboost/doc/dg/concepts/python-reference_catboost_fit-docpage/)

'metric_period' introduced into command-line version at the moment. We'll add it into python wrapper shortly. Thank you for this issue!

**Comment by sab** [comment]
'metric_period' is now available in python wrapper. Please use version 0.5.2.1
