### ISSUE TITLE
[ENH]: daily dev snapshot release

### ISSUE THREAD

**Issue by celestinoxp** [catboost/catboost#2131]
For many people, try install develop version from source it's very hard.

Opinion: Exists many packages with direct link to develop packages.
Example of scikit-learn with command:  <code>pip install --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple scikit-learn</code>

More details about scikit-learn develop installation: https://scikit-learn.org/stable/developers/advanced_installation.html#installing-nightly-builds

Advantages: Ease to install latest changes and find latest possible bugs

It makes sense?

**Comment by andrey-khropov** [comment]
The problem is that CatBoost artifacts are very big (many OSes and CPU architectures and CUDA packages also contain compiled code for many CUDA compute architectures) so frequent releases will overwhelm disk resources on PyPI. We don't want to abuse their generosity providing free package storage. We'll try to think about some kind of compromise here, maybe some dev snapshot releases but with decreased frequency.
