### ISSUE TITLE
Bug in get_object_importance in R

### ISSUE THREAD

**Issue by ThomasWolf0701** [catboost/catboost#2155]
Problem:
catboost version: 1.0.6
Operating System: Windows
CPU: Intel
 
 When using the catboost.get_object_importance function in R, I get the following error:
 Non-Multiclassification and Non-MultiTarget compatible metric (RMSEWithUncertainty) specified for a multidimensional model
 
which is the same as already described here for get_feature_importance in R:  https://github.com/catboost/catboost/issues/1438

This bug has already been fixed so I suppose the get_object_importance one  should he fixable too.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
except the obscure exception message, this is the expected behavior, and not a bug

catboost calculates object importance based on theory which assumes that predictions are one-dimensional
this is not the case with RMSEWithUncertainty which predicts mean and stddev
https://catboost.ai/en/docs/concepts/python-reference_catboost_get_object_importance --> https://arxiv.org/abs/1802.06640 

i fixed catboost to react in a more comprehensible way, and added to the doc the list of losses supported in object importance

it seems possible to calculate object importance independently for each dimension of multi-dimensional prediction
if you have a strong evidence that such information would be useful, please create a new issue
