### ISSUE TITLE
Static library misses logger dependencies

### ISSUE THREAD

**Issue by EdvardD** [catboost/catboost#2187]
Problem: static library misses some dependencies
catboost version: 1.11
Operating System: Ubuntu 20.04

I'm following instructions from [here](https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper) to build a static library and link it to my external binary (I use cmake in my project). It seems that the static lib isn't fully self contained.

I wonder if this is a known issue and how it could be fixed?

Here are linking errors: https://pastebin.com/RtAMytpw

**Comment by israelshenkar** [comment]
i'm getting the same form 1.1

**Comment by israelshenkar** [comment]
@EdvardD i've managed to compile it after removing the GLOBAL in two files:
catboost/catboost/libs/model/ya.make 
catboost/library/cpp/logger/ya.make

**Comment by j0tunn** [comment]
Looks like:
- https://github.com/catboost/catboost/issues/1376
- https://github.com/catboost/catboost/issues/1298

**Comment by andrey-khropov** [comment]
The issue is that the static library needs two parts:
 - The first one that contains symbols that require forced initialization.
 - The second part that contains all other symbols.
 
 It has been mentioned in https://github.com/catboost/catboost/issues/1376#issuecomment-670406994.
 
 There've been issues with Ya Make and Make based builds that sometimes one of these parts had been missing.
 
 Recently, CatBoost has switched to CMake-based build and now both parts are created properly and building static evaluation library now works on Windows as well.
 
 I've fixed and expanded documentation at https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper that now up to date with these changes.
