### ISSUE TITLE
Cannot install catboost on AWS T4G (linux/unix) architecture! 

### ISSUE THREAD

**Issue by ryanshrott** [catboost/catboost#2210]
Problem: Cannot install catboost on Amazon Linux (UNIX) 
catboost version: 1.1
Operating System: Amazon Linux
CPU: AWS t4g.small (Linux/UNIX)
GPU: None

Error message:
$ pip3 install catboost
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement catboost (from versions: none)
ERROR: No matching distribution found for catboost

What is the best/easiest workaround to "pip3 install catboost" on AWS linux (UNIX) architecture?

**Comment by andrey-khropov** [comment]
That is because AWS t4g.small has AWS Graviton2 processor that has arm64 architecture. CatBoost as of 1.1 had no wheels or source distribution compatible with arm64 architecture available on PyPI but they will be available in release 1.2: #2091.

You can try RC version now: https://github.com/catboost/catboost/issues/2213#issuecomment-1515000094

**Comment by andrey-khropov** [comment]
With the release 1.2 wheels for Linux aarch64 now available on PyPI so this problem should be solved now.
