### ISSUE TITLE
 After I set CFLAGS+=-fPIC in catboost/build/conf/compilers/gnu_compiler.conf, the following error is reported

### ISSUE THREAD

**Issue by slimcheng3** [catboost/catboost#2220]
Problem:  After I set CFLAGS+=-fPIC in catboost/build/conf/compilers/gnu_compiler.conf, the following error is reported.
catboost version: 1.1.1
Operating System: linux x86
CPU: 
GPU:
![image](https://user-images.githubusercontent.com/38289883/200725695-c5b20402-7e33-4944-b692-84f9eebcbba3.png)

**Comment by slimcheng3** [comment]
@AlexeySalmin  help me pls;

**Comment by andrey-khropov** [comment]
CatBoost has switched to CMake-based build since release 1.2. [Here's the documentation](https://catboost.ai/en/docs/installation/python-installation-method-build-from-source-linux-macos). `PIC` if now regulated by CMake's [CMAKE_POSITION_INDEPENDENT_CODE flag](https://catboost.ai/en/docs/installation/build-native-artifacts#cmake-options-and-definitions)

**Comment by andrey-khropov** [comment]
> CatBoost has switched to CMake-based build since release 1.2. [Here's the documentation](https://catboost.ai/en/docs/installation/python-installation-method-build-from-source-linux-macos). `PIC` if now regulated by CMake's [CMAKE_POSITION_INDEPENDENT_CODE flag](https://catboost.ai/en/docs/installation/build-native-artifacts#cmake-options-and-definitions)

@slimcheng3  Are you able to build successfully now or you need to build from the older revision for some reason?

**Comment by andrey-khropov** [comment]
As no information has been provided for quite some time I am closing this for now. Feel free to reopen with additional information if needed.
