### ISSUE TITLE
MultiQuantile non monotonic with alpha

### ISSUE THREAD

**Issue by adiellm** [catboost/catboost#2317]
Problem:
catboost version:
Operating System:
CPU:
GPU:
Hello, I am trying to use `MultiQuantile` in a similar way to [this tutorial](https://towardsdatascience.com/a-new-way-to-predict-probability-distributions-e7258349f464). I have noticed that the predictions are not necessarily monotonic increasing with the quantile alpha.

I wonder what is causing that and if there's something that can be done in order to get it to be monotonic as expected?

Thanks

**Comment by abcde-1447** [comment]
@adiellm Hi, I have similar issue, just wonder have you figured this out?  If at each leaf we make multiple predictions based on alphas, the predictions should be monotonic, though I am not sure how this loss is implemented internally

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
hi @adiellm ! hi @abcde-1447 ! 
🤝 🤝🤝
no surprise, we train a model predicting for each alpha independently, and do not enforce monotonicty

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
it is just faster than training multiple models one-by-one
and yes, we generate multiple predictions for each sample

we looked at solutions like https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3242516/, and finally decided to go with the simple implementation because the app using multi quantile regression tolerates small errors

**Comment by abcde-1447** [comment]
@Evgueni-Petrov-aka-espetrov 

> yes, we generate multiple predictions for each sample

Can you explain this in more details?  Does it mean we use **same tree** for predicting multiple quantiles at each leaf node, or we use multiple trees (meaning different splits, etc) and each predicting a separate quantile?

**Comment by abcde-1447** [comment]
@Evgueni-Petrov-aka-espetrov 

Got it, thanks!  If it is the same tree, then I am kind of confused why this "crossing" would happen, since to minimize the MultiQuantile loss, for each leaf node we should have strictly increasing predictions with alphas, so there should not be any crossing at leaf node level.  And since final predictions are just aggregation of multiple leaf nodes, the crossing should not happen either.  Can you help me understand why this crossing happens?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
yep, if we get a reproducer for significant crossing...
