### ISSUE TITLE
Catboost 0.6 cannot load model created with catboost 0.2.2

### ISSUE THREAD

**Issue by ms-lilibeth** [catboost/catboost#235]
```
CatboostError                             Traceback (most recent call last)
<ipython-input-7-168d201803e6> in <module>()
----> 1 catboost.CatBoostClassifier().load_model(p)

/usr/local/lib/python3.5/dist-packages/catboost/core.py in load_model(self, fname)
   1045         if not isinstance(fname, STRING_TYPES):
   1046             raise CatboostError("Invalid fname type={}: must be str().".format(type(fname)))
-> 1047         self._load_model(fname)
   1048         return self
   1049 

_catboost.pyx in _catboost._CatBoostBase._load_model()

_catboost.pyx in _catboost._CatBoost._load_model()

_catboost.pyx in _catboost._CatBoost._load_model()

CatboostError: catboost/libs/model/model.cpp:430: Incorrect model file descriptor
```

Rollback to the version 0.2.2 solves the problem.

**Comment by annaveronika** [comment]
We have changed the model format (breaking changes). Since 0.4 or 0.5 the model is not breaking anymore, we switched to flatbuffers. If you have trained your model with an old version of catboost and have only numerical features, you can do the following: convert your model to coreML using old version of catboost + load the coreML model with the new version. The code for that will be available this week. Will this solve your problem?

**Comment by ms-lilibeth** [comment]
@annaveronika, yes, it will. Thank you!

**Comment by kizill** [comment]
In 0.6.2 we released coreml import (oblivious trees) possibility, you only have to export your pre 0.5 models in coreml format, update catboost to 0.6.2 and import them from coreml. You can try this code snippets:
```python
model = CatBoost()
model.load_model('your_model.cbm')
model.save_model('your_model.coreml', format="coreml")
```
After updating to 0.6.2 do:
```python
model = CatBoost()
model.load_model('your_model.coreml', format="coreml")
model.save_model('model.cbm')
```

**Comment by annaveronika** [comment]
If this doesn't work, please reopen the issue

**Comment by mtrsk** [comment]
For anyone having this error with `Incorrect model file descriptor` and also happens to use [git lfs](https://git-lfs.github.com/), make sure `lfs` configured correctly, otherwise you'll download pointers to the files instead of the actual models and spend some time guessing what actually gone wrong.

To be sure, check if your models are not some 100kb files:
```
$ du -sh your_project/ml_models/*
6.6M	your_project/ml_models/model01
8.6M	your_project/ml_models/model02
```
