### ISSUE TITLE
Online Learning Tutorial

### ISSUE THREAD

**Issue by algomaschine** [catboost/catboost#2428]
Problem: online learning
catboost version: latest
Operating System: Windows Server 2016
CPU: 64core

Dear Developers, is there a decent tutorial for online learning, aka learning withy realtime data which explains all the nitty-gritty of the process? It's been mentioned in the education video by Anna Veronika back in 2019, but I could only find very basic examples. Pls advise. Thanks!

**Comment by ek-ak** [comment]
Hello! 
Please specify the exact video where was the information about the tutorial, so that we can answer what tutorial was mentioned.
If you have new data you can either continue learning from baseline or retrain the model on new data. CatBoost is fitted fast enough so usually there are no problem to train a new  model.

**Comment by andrey-khropov** [comment]
No additional info is provided, so I am closing this issue. Feel free to reopen with more details if necessary.
