### ISSUE TITLE
Add parameter allow_const_target

### ISSUE THREAD

**Issue by PetoLau** [catboost/catboost#266]
Hi,
I am using R package version of `catboost` (v. 0.6.2) for an automatic creation of a large number of predictions for a regression task.
It can logically happen that target variable has sometimes zero variance. In this scenario `catboost.train` gives error:
`Error in catboost.train(learn_pool = train_pool, params = params) : 
  catboost/libs/train_lib/train_model.cpp:331: All targets are equal`
Therefore, I have to create large number of if else statements in my code.
Would it be possible to change error creation (stop of training) to just warning message and train a model?
Thanks

**Comment by annaveronika** [comment]
We decided to throw an error in this case because it helps people to find errors - it is a very common error that target is constant because of some issues when building the dataset. Very often people don't see this error if we don't throw it - they just go with a bad model. Unfortunately there is a tradeoff here, but we are trying to make the best decision, we decided to stay with the error to make it clear for people that they have a problem in dataset.
To solve your problem you can comment the line with the check in code and recompile the project, it will work.

**Comment by annaveronika** [comment]
Actually a possible solution would be to add a new parameter bool allow_const_target that is false by default. I think we can implement this one

**Comment by PetoLau** [comment]
@annaveronika Thank you for the answers. That bool would be perfect!

**Comment by annaveronika** [comment]
@PetoLau Would you be interested in adding this feature?

**Comment by PetoLau** [comment]
I am sorry, but I have not capacity for this now.

**Comment by annaveronika** [comment]
@andrey290494 Sure, I'll explain in russian: constant target значит, что все метки (== target, == label) в обучающем датасете имеют  одинаковое значение.

**Comment by annaveronika** [comment]
The code is on github now, you can build from source to use new option allow_const_label.
