### ISSUE TITLE
(Python) Uncaught C exception leads to crash like #134

### ISSUE THREAD

**Issue by JYLFamily** [catboost/catboost#356]
Problem: {

address -> 0x107934088
    what() -> "catboost/libs/algo/full_features.cpp:301: There are NaNs in test dataset (feature number 93) but there were no NaNs in learn dataset"
    type -> TCatboostException

}
catboost version: {
0.8.1.1
}
Operating System: {linux}
CPU、GPU:{linux server}

Problem like this https://github.com/catboost/catboost/issues/134 ?

**Comment by annaveronika** [comment]
Previous problem was that there was a crash. Currently it's an exception, and it's expected behavoir. If no nans were in train, then we don't know how to handle nans in test.  Usually this means that you have some problem in building your dataset. To have no exception you need to replace nans in test for features that had no nans during training with some value.

We are planning to add a flag to allow features with no nans in train but with nans in test. But using this flag will hide potential problems in your dataset.

**Comment by JYLFamily** [comment]
Thank you for your answer.

**Comment by avloss** [comment]
I can't exactly reproduce, but it seems sometimes it's an exception and sometimes it's "kernel died" without a message (depending on the number of columns).

Regarding "expected behaviour" -imagine I've been generating columns at "industrial scale" and say have 500 of them, with some being n/a. I have 5 fold validation. Ensuring that every fold has at least some n/a s for every feature is non-trivial. In one of your talks, you've said that Catboost is treating N/As as minimum OR maximum. Can't there be a default setting to make CatBoost do just that? even if N/As do not come up in the train. I mean that's what I would do manually anyways - what options do I have? Lightgbm doesn't seem to be complaining about this issue.
