### ISSUE TITLE
New NaNs in eval_set kill Jupyter kernel (Python)

### ISSUE THREAD

**Issue by Ingvar-Y** [catboost/catboost#389]
Problem:
When your train dataset doesn't contain null values in a certain column but your validation dataset (specified by `eval_set=`) does, it kills Jupyter kernel. It happens under both Windows and Linux but under Linux catboost throws an exception to Linux terminal which allowed me to trace the issue:
```
uncaught exception:
    address -> 0x107906488
    what() -> "catboost/libs/algo/full_features.cpp:301: There are NaNs in test dataset (feature number 281) but there were no NaNs in learn dataset"
    type -> TCatboostException
```
Linux
catboost version: 0.8.1
Operating System: SUSE Linux Enterprise Server 12 SP2
CPU: Intel Xeon E7-8880 v4, multiple

Windows
catboost version: 0.8.1
Operating System: Windows 10 Enterprise
CPU: Intel Core i5-5300U

**Comment by annaveronika** [comment]
We fixed the crash, it will throw an exception now on Windows. We didn't remove the exception, because it is intentional.
If you have not seen nan values in train data, you don't know what to do with nan data in test. The only thing you can do - replace it with something, for example with 0 or with +-infty. But since you haven't seen this in train, you don't know which way will work.

That's why we decided to throw an exception in this case. This way we warn you that you should either add examples with nan to train or replace nans in test with something that you think will work.

We plan to add a flag later to allow this behavoir, but it's better to provide train and validate from the same distribution, with nans present in train.

**Comment by Ingvar-Y** [comment]
There is no problem with the exception - a lot of ML algorithms can't handle NaN data at all so having the same distribution is a minor demand.

IMHO, the main inconvenience is (was?) that you don't get the exception inside Jupyter Notebook. When your code doesn't work you want to see the reason for it immediately.

**Comment by annaveronika** [comment]
Yes, thanks a lot for reporting this, we made a fix, now there should be an exception.
It'll be on pypi in the next release.
