### ISSUE TITLE
negative value in mlogloss

### ISSUE THREAD

**Issue by munitech4u** [catboost/catboost#401]
Problem: Is it expected for the mlogloss to have negative value and then increase with number of iterations?

I am seeing -ve values in mlogloss training of catboost like: 

 -1.394..
-1.357..
-1.336..
....

However when I run multi_logloss in lightgbm, I am seeing : 

0.631
0.5512
0.5413..
..

They both are moving in different directions. Is this expected? 

catboost version: {0.8.1.1}
Operating System: {Windows 10}
CPU: {i7}
GPU: {NA}

**Comment by sergmiller** [comment]
Yes, it is. As you can [see](https://github.com/catboost/catboost/blob/master/catboost/libs/metrics/metric.cpp#L461) catboost uses positive logarithms in mlogloss  (oppposite to [lightgbm](https://github.com/Microsoft/LightGBM/blob/master/src/metric/multiclass_metric.hpp#L159)), so you need to maximize this metric as an objective, instead of minimizing it as a loss.

**Comment by munitech4u** [comment]
ok. thanks
