### ISSUE TITLE
No eval_metric saved / displayed in v. 0.9.1.1

### ISSUE THREAD

**Issue by snovik75** [catboost/catboost#435]
Latest 0.9.1.1 does not show/save eval_metric (AUC in my case)
 
After downgrading to 0.8.1 both learn and test files have 'AUC' saved also displayed during training. 

catboost version: 0.9.1.1
Operating System: linux

**Comment by annaveronika** [comment]
As I replied in #365 it is expected behavoir.
Starting from last release AUC and PFound are not calculated by default on train dataset.
The reason is that those metrics are very expensive to calculate, so their calculation is the bottleneck of the training.
If you want to calculate them anyway you need to write AUC:hint=skip_train~false
I would also suggest to use metric_period=20 in case if it will work slowly. This way metric value will be calculated only on each 20-th iteration.

**Comment by snovik75** [comment]
What have stopped you to have this flag set by default?

I believe the whole community would appreciate if you stopped introducing breaking changes or at least have them explicitly documented on the website. It is not the first change that I encountered with catboost when after an upgrade my previous code stops working and I have no clue why and how to fix it and this pushes me away from catboost even further.

**Comment by annaveronika** [comment]
We are very sorry for this inconvenience. But it is worth it because now if you have a large dataset your training will work much faster. You must know about this issue with AUC metric, otherwise you could not speed up your training. So now you know.
About documentation - the change was described in the release, but it didn't come to documentation instantly. We are trying to match documentation with all the changes in the releases, but sometimes there are delays.
So I would suggest to read all the release descriptions, I hope it will help in the future to not have version problems.
