### ISSUE TITLE
Add tag to the tutorials repository

### ISSUE THREAD

**Issue by b0noI** [catboost/catboost#463]
Please add either tags or branches to the tutorials repository. It is critical to now which commit from the tutorials repository should be used for a particular catboost version. Current master of tutorials is not compatible with the latest public catboost 0.9.1.1 (see #462 )

**Comment by annaveronika** [comment]
The tutorials repo is in complete sync with the main repo. In fact it is a part of main repo (https://github.com/catboost/catboost/tree/master/catboost/tutorials), which is automatically synced to separate repository, so that users don't have to clone the whole repo to only get tutorials. Thanks a lot for reporting the bug in tutorial - we are looking into that, we'll answer in the issue in short time.

**Comment by annaveronika** [comment]
So regarding the suggestion - we cannot add tags and branches for this repo. But you are right that we should not break the tutorials functionality. I hope, we'll have more frequent releases and we'll not meet this problem again.

**Comment by annaveronika** [comment]
So as I explained, we cannot add the tag, thus, closing the issue. Hope everything works for you now.
