### ISSUE TITLE
_catboost.CatboostError: bad object for id: nan

### ISSUE THREAD

**Issue by xxllp** [catboost/catboost#482]
Problem: {problem description}
catboost version: {0.10.2}
Operating System: {OS}
CPU: {CPU}
# GPU: {GPU}
I don't  know why it can't  have nan  in the data ? 
  File "_catboost.pyx", line 1022, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 1028, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 1151, in _catboost._PoolBase._set_data_and_feature_names
  File "_catboost.pyx", line 1133, in _catboost._PoolBase._set_data_from_generic_matrix
_catboost.CatboostError: Invalid type for cat_feature[880,2]=nan : cat_features must be integer or string, real number values and NaN values should be converted to string.

**Comment by annaveronika** [comment]
The reason for that is that we want the algorithm to work exactly the same when working with a file or with a matrix. What we do with categorical features is the following: we look on the value of the feature as a string, calculate hash from it and then work with this hash value.
Now, if you allow nan values to be present, then there must be a unique string that identifies it, so that we get the same hash when reading from file or from matrix.
But it is not true - in file you might specify it as one string, and in matrix it will be a different string when you do to string from it.
The same is true for floating point values. That's why we only allow integer values and strings.

**Comment by xxllp** [comment]
I see

**Comment by Yufei-Z** [comment]
when i train the model, train data has float and it works

**Comment by Yufei-Z** [comment]
but in test set,
Invalid type for cat_feature[non-default value idx=0,feature_idx=13]=6.0 : cat_features must be integer or string, real number values and NaN values should be converted to string.

**Comment by annaveronika** [comment]
If train data has float features, train should fail also. Please check with the latest version that it does.

**Comment by Yufei-Z** [comment]
but it does train perfectly... and i get a model with plot.

**Comment by annaveronika** [comment]
It will not train starting from the next version, we have fixed the checks now. In the future we plan to add a flag allow_float_categorical will be False by default. For now please convert categorical features to strings or to integers, and use this types.

**Comment by Yufei-Z** [comment]
can i convert float to str? can catboost handle it?(there maybe  lots of different value)
best regards

**Comment by annaveronika** [comment]
You should convert your categorical feature values to strings before passing it to catboost. And pass it to CatBoost in python DataFrame, where categorical columns will have type object or Categorical.

**Comment by aksharag** [comment]
Maybe the order of features you are passing in test is not the same as train, please check that too.
