### ISSUE TITLE
R - get_feature_importance() doesnt have attribute "names" as before

### ISSUE THREAD

**Issue by raulcarlomagno** [catboost/catboost#499]
Problem:
In version 0.10 i did this to get a data frame with features importance, feature name + its importance e

features_importance <- catboost.get_feature_importance(model, pool = train_pool, fstr_type = "FeatureImportance")

features_importance <- data.frame(feature = attr(features_importance, "names"), importance = features_importance)

now, this returns NULL
attr(features_importance, "names")

is this the same?
dimnames(train_pool)[[2]]

catboost version: 0.10.3
Operating System: Windows 10
CPU: Intel I7-7500U
GPU: NVIDIA GeForce 940MX

**Comment by AxelEriksson0** [comment]
You can merge the column names from the dataset with the get_feature_importance result because the order is still intact.

In R:
catboost_feature_importance <- catboost.get_feature_importance(model = catboost_model)
catboost_feature_importance_with_column_names <- data.frame(column_name = colnames(catboost_features), importance = catboost_feature_importance)

**Comment by dbakshee** [comment]
> is this the same?
> dimnames(train_pool)[[2]]
Yes. The workaround for 'FeatureImportance' is 
features_importance <- data.frame(feature = colnames(train_pool), importance = features_importance)

And thank you for reporting the issue, we'll fix it.

**Comment by dbakshee** [comment]
Hi @raulcarlomagno 

The issue should be fixed with commit 4391191dfa35e047e0b168bcefd6bec2ced3322b

Once you obtain `feature_importance` with `catboost.get_feature_importance(...)`, you should be able to get the names of the rows (that is, feature names) with `rownames(feature_importance)`.

We decided not to provide `names(feature_importance)` because the object returned by `catboost.get_feature_importance` is a `matrix`, not an atomic vector.

Thanks
Dima

**Comment by Steviey** [comment]
Very poor deccission- causing many problems in R.

**Comment by annaveronika** [comment]
> Very poor deccission- causing many problems in R.

Could you please create a new issue with detailed explanation of the problem and proposed solution?

**Comment by Steviey** [comment]
It took me a full day, to figure out what's going on here - having feature importances without feature names. It needs two different workarounds for param: type='FeatureImportance' vs. type='ShapValues'.

`"catBoostNativeImp" = {
                impMat <- catboost.get_feature_importance(myModel 
                            ,pool = train_pool
                            #,type = 'ShapValues'
                            ,type = 'FeatureImportance'
                            ,thread_count = -1)
                
                colVect<-append(dataList$yName,colnames(train_pool))
                impDf <- data.frame(feature=colVect, importance = impMat)
                print(class(impDf))
                View(impDf)
                stop()
            },
            "catBoostNativeShap" = {
                impMat <- catboost.get_feature_importance(myModel 
                            ,pool = train_pool
                            ,type = 'ShapValues'
                            #,type = 'FeatureImportance'
                            ,thread_count = -1)
                myCols<-colnames(train_pool)
                myCols<-append(dataList$yName,myCols)
                colnames(impMat)<-as.vector(myCols)
                impMat<-round(impMat,4)
                impDf<-as.data.frame(impMat,stringsAsFactors=F)
                View(impDf)
                stop()
            },`
