### ISSUE TITLE
Magic default value of "decay" parameter (0.99) for YetiRank*

### ISSUE THREAD

**Issue by kslazarev** [catboost/catboost#517]
Problem: Missed docs. Magic constant 0.99 for YetiRank* loss metric. 
Catboost version: master

https://github.com/catboost/catboost/blob/ece12146e330083d10c54275baf8388b94f81527/catboost/libs/options/loss_description.cpp#L81-L89

- Why this parameter has default value equal to 0.99 nor 0.999 nor 0.9? PFound metric has default value equal to 0.85, why not 0.99. Why metrics have difference in default parameter value?

https://tech.yandex.com/catboost/doc/dg/concepts/loss-functions-docpage/#loss-functions__ranking

- For what case in ranking default value (0.99) of "decay" parameter was optimized? For example, 10-top ranking, 100-top ranking, 1000-top ranking or something else.
- How to choose this parameter for ranking task? I think this parameter really affect on the quality of different *-top ranking, the choose of RULES features and catboost parameter tuning (depth, L2 reg, ...), isn't it? So we need to choose this parameter before all CVs depend on the ranking task.

**Comment by annaveronika** [comment]
Hi Kirill, thanks a lot for your question. Yes, we have some magic constants in the code, which in our experience work well. We don't plan to make them all public parameters, otherwise there would be too many parameters. But if you strongly feel that there is much sense for your dataset to change it, you can try recompiling the code with some other number.
We do provide documentation and instructions how to tune parameters for all parameters that we think it is important to sweep.

**Comment by annaveronika** [comment]
Actually we have put it out as a parameter, and you are right, we don't explain how to tune it.
We should write a tutorial on how to tune ranking. I'll put planned on the issue, we will do it at some point. Sorry for misunderstanding.

**Comment by kslazarev** [comment]
@annaveronika Thank you for planned
