### ISSUE TITLE
Strategies for GPU memories

### ISSUE THREAD

**Issue by jy03189211** [catboost/catboost#527]
Problem: {splitting the dataset into smaller size for GPU DRAM limit}
catboost version: {latest release}
Operating System: {windows}
GPU: {GTX 760}
python 3.6.6

I am usting dataset about 30k rows and 50 columns,
and I have a relatively small gpu ram size about 2G
It works fine without  auto hyperparameter tuning.

However I was trying to tune the parameter  with baysian optimization package such as skopt.
As the interation in the auto optimization packeage increases, the program died
the seach space:
```
    search_spaces = {
        'learning_rate': (0.01, 1.0, 'log-uniform'),
        'max_depth': (3, 15),
        'n_estimators': (2000, 8000),
        #'colsample_bylevel': (0.01, 1.0, 'uniform'),
        'subsample': (0.01, 1.0, 'uniform'),
        'reg_lambda': (1e-3, 1, 'log-uniform'), 
    }, 
```
```
Application terminated with error: PyInit__catboost+361884 (0x7FFDDB756ABC)
??+0 (0x7FFDDB4A6CC9)
PyInit__catboost+7220302 (0x7FFDDBDE116E)
PyInit__catboost+7215790 (0x7FFDDBDDFFCE)
PyInit__catboost+7221915 (0x7FFDDBDE17BB)
PyInit__catboost+7207150 (0x7FFDDBDDDE0E)
PyInit__catboost+7208587 (0x7FFDDBDDE3AB)
??+0 (0x7FFDDB6B34A4)
??+0 (0x7FFDDB6ADA4E)
PyInit__catboost+17157000 (0x7FFDDC75B0A8)
BaseThreadInitThunk+20 (0x7FFE38153034)
RtlUserThreadStart+33 (0x7FFE39271461)
```

catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:305: Error: Out of memory. Requested 1312 MB; Free 1074.135175 MB

My question, 
1.is there a recommended way for splitting the datasize into smaller size, then train and save the subset of the data stepwise at each time.
2. I have not tried the hypropt package in your example code. Will there be GPU memory issue as the interation increases?

**Comment by Noxoomo** [comment]
Hi!

I think you tried to learn trees with big values of depth (like 10-16 instead of default 6 one). The deeper tree you learn => more memory you will need. Especially on small datasets (with <50k rows) — we'll use ordered boosting instead of classical one for such small datasets and this boosting type cause big memory consumption for deep trees.

I suggest printing information about what parameters cause OOM exception. 

If you need deeper trees, you could explicitly set boosting type option to boosting_type="Plain". This should allow training deeper trees than you'll be able with the default option

**Comment by annaveronika** [comment]
https://github.com/catboost/catboost/issues/428 - we will add more information when fixing this issue.
The current one I'm closing as duplicate.
