### ISSUE TITLE
`learn` key in model.best_score_

### ISSUE THREAD

**Issue by AndreyGurevich** [catboost/catboost#539]
Problem: After training a catboost 0.11 model property model.best_score_ does not contain key `learn`. It contains only `validation_0`. Now it looks like this:
`{'validation_0': {'RMSE': 663.9518541090044}}`

Catboost 0.10.3 had additional key:
`{'learn': {b'RMSE': 660.518541090044}, 'validation_0': {b'RMSE': 663.9518541090044}}`
It`s great that you fixed byte-encoding, but how can I get learn metric? Did not find it in https://github.com/catboost/catboost/releases
catboost version: 0.11
Operating System: Ubuntu 16
CPU: {CPU}
# GPU: {GPU}

**Comment by AndreyGurevich** [comment]
Feel myself like that guy with spacebar: https://xkcd.com/1172/ :(
I can use any way to get best/last learning score, but can`t find it in 0.11. `model.evals_resul` contains only validation score too.

Is there any method to get learn score in 0.11?

**Comment by annaveronika** [comment]
You can look the value in tsv file with learn error values or use 0.10.*. Please be patient the pr with returning back the score on learn is on it's way, we'll push the next version on pypi today.
Btw some errors are not calculated on train by default (AUC, NDCG, PFound), because they are expensive to calculate.

**Comment by AndreyGurevich** [comment]
Thank you!
MAE, RMSE are enough.

**Comment by kizill** [comment]
Released in 0.11.1
