### ISSUE TITLE
Random seed issue on classifier when run on GPU

### ISSUE THREAD

**Issue by karacor** [catboost/catboost#546]
Each time different results are generated when a classifier model is run on GPU, using exactly the same parameters and the same random_seed
catboost==0.11.1
Operating System: Windows 10 x64
GPU: Nvidia 960

**Comment by Noxoomo** [comment]
Hi!

GPU version doesn't guarantee the same results for the same parameter.  (There are atomic operations in some computation blocks for which we can't guarantee reproducibilit, because different sum order of floats gives different results).

Btw, usually the difference between runs should be quite small

**Comment by karacor** [comment]
Yes, the perturbations are small indeed. Thanks for the clarification.
