### ISSUE TITLE
Understanding cuda installation walkthrough

### ISSUE THREAD

**Issue by VKON** [catboost/catboost#555]
Problem: {Using GPU instead of CPU requires several complicated installation steps where particular version of drivers and software updates need to be matched (graphical card drivers, CUDA toolkit, VS, MSVC compiler). this could be demonstrated with a simplified workflow for better understanding}
catboost version: {0.11.1}
Operating System: {win 7}
CPU: {CPU}
GPU: {GeForce GT 730M}

**Comment by timchurches** [comment]
Just to note that the binary install of CatBoost for R on Windows works fine using the additional arguments detailed in this thread: https://github.com/catboost/catboost/issues/538 and since version 0.10 the binaries statically link the CUDA libraries, so you don't need to install all the CUDA libraries, although you need to have compatible CUDA drivers installed, it seems.

**Comment by VKON** [comment]
Thanks Tim,

also for your confirmation that the GPU version can be installed earlier (on windows 7?)

So the drivers, this is the problem. Its not that I need the CUDA drivers, I also need to update my geforce drivers, so they fit into the 'Training on GPU requires NVIDIA Driver of version 390.xx or higher' restriction, which are a pre-requisit from catboost devs in their documentation. I checked, my card is eligible for CUDA operation, so was already overly enthusiastic while downloading both the cuda toolkit and the geforce drivers.  

Just to give you a feeling how it feels when things dont go quite as smoothly as you think: 

I had a bluescreen for over 4h just today, and it was really difficult what exactly was not right after all the many different updates (not just the graphics driver). Not so nice...now I kind of dont know what to do with my new driver, or which one to keep as selecting the wrong one (or going back to some previous version - not sure which one) apparently is the cause for the blue screen. 

If I shut down the PC now I might go all bluescreen again with the next startup (if I leave my graphics card driver turned on, so I better turn it off for now). The error code seemingly has nothing to do with Geforce: its the dlkmd.sys file that causes a page_fault_in_nonpaged_area problem. Removing DirectLink is not possible as some programs depend on it, so I am somewhat trapped there.

Open for ideas. Who else dares updating all their drivers and try the CUDA-run? I am sure it is possible.

**Comment by timchurches** [comment]
Yes, you only need v390.x or later of the NVIDIA driver for Windows installed to use the CatBoost binary installations (for R or python), it isn't necessary to install the entire set of CUDA library files, although just downloading the (massive) CUDA package may the easiest way to get the latest driver. The CUDA library files do no harm is installed, but they aren't needed since they are already statically compiled into the binaries supplied by Yandex.

We're see about a 2x speed-up of training on a Windows desktop with a fairly low-end NVIDIA GeForce 630 GPU card, and a 40x speed-up on a 16-core linux server with a single NVIDIA Tesla V100 GPU card (in AWS). That's fast enough for us, but at some stage we will see if it goes even faster on a multi-GPU server...

**Comment by annaveronika** [comment]
@VKON Should I close the issue? I'm not sure if we have to do anything on our site.

**Comment by VKON** [comment]
@annaveronika yes please, thanks for help everyone!
