### ISSUE TITLE
Catboost binary format much faster than c++ code

### ISSUE THREAD

**Issue by theycallhimavi** [catboost/catboost#614]
Problem: I have seen that using catboost binary format, i get around 1000 times more qps than by compiling the export as C++ code using gcc with Optimizations enabled. Is there any algorithm level optimization that is used in the binary format, which is not enabled in c++ code?
catboost version: latest
Operating System: Linux and MacOS
CPU: Intel 7th gen Xeon Platinum

**Comment by kizill** [comment]
There are two big differences between c++ evaluation of binary model and model exported as c++ code:

1. When model contains only float features, speed differs due to SIMD vectorization (we internally apply on batches with max length of 128 objects).
2. When model contains categorical features (i guess it's your case?) there could be really big speed difference due to non-optimal catfeature hash resolve in exported cpp model.
So, i recommend you to use our C API or C++ wrapper over it: https://github.com/catboost/catboost/tree/master/catboost/libs/model_interface as it gives stability and you can update model without recompilation :)

**Comment by annaveronika** [comment]
@theycallhimavi Should I close the issue? Do you maybe need help with faster ways of applying the model?

**Comment by theycallhimavi** [comment]
@annaveronika @kizill yeah, i have now moved to the C API. I figured it would be better in the long term. However in my quest to speed up the C++ code, i was able to achieve ~100x speedup for multiple requests by caching over tree splits. I can raise a Pull Request if you guys believe that is something that would be helpful for the project.

**Comment by annaveronika** [comment]
This is great, we are happy to have your PR!
