### ISSUE TITLE
Выдает один и тот же предикт

### ISSUE THREAD

**Issue by yolopoks** [catboost/catboost#638]
Problem: Хотелось бы задать вопрос, хорош ли катбуст при классификации на примере датасета, где первое поле это какой то текст, а во втором категория, к которой этот текст нужно отнести, обучить его и чтобы он сам определял, к какой категории относится тот или иной текст?
Обучил на 100к данных текст-категория
При предикте все время выдает первую категорию
Он будто не понимает, что я передаю ему в тесте
И, соответственно, процент точности 33 процента только потому, что из всех этих 100к записей 33 процента это именно эта категория

**Comment by annaveronika** [comment]
We don't currently support text features. But actually we are working on that.

**Comment by annaveronika** [comment]
Very sorry for a long response, we didn't have time to look through the issues for a while. Does my previous comment answer your question, do you need any other info?

**Comment by annaveronika** [comment]
I have created one more issue https://github.com/catboost/catboost/issues/697 - you can track this one to see when text features are added. I close this issue then, because there is no problem with constant prediction - it's rather that we don't support text features jet.
Thanks for your feedback to the lib!
