### ISSUE TITLE
Choosing between CatBoostClassifier and CatBoostRegressor for a highly skewed regression target

### ISSUE THREAD

**Issue by gitmario** [catboost/catboost#687]
I'm working on a problem that can be addressed both as a regression and a classification task, and I would really appreciate your advice on how to best use CatBoost.

The aim of the model to predict a customer's lifetime value (LTV) based on demographic information (age, country etc.). For 95% of the customers, LTV is zero (they don't buy any product), and for 5% of the customers, LTV can vary by orders of magnitude in the range [1-100].

I would really appreciate your input on two possible approaches:

1) Treat the problem as a simple regression task, using CatBoostRegressor on the entire dataset

2) Train a CatBoostClassifier to predict if a customer will make a purchase (binary target in {0, 1}). Then train a CatBoostRegressor on the subset of customers who made a purchase (continuous target in the range [1-100]). To predict the LTV of a new customer, multiply the predicted probability to buy at least one product of the CatBoostClassifier by the predicted LTV (conditioned to the fact that the customer made at least one purchase) of the CatBoostRegressor.

Some additional questions:
- Should I try to use a different loss_function than "RMSE" for CatBoostRegressor?
- Should I try to use class_weights for CatBoostClassifier?
- Are there any other hyperparameters to tune, best practices etc. to address this kind of problem effectively?

Another (minor) issue is that some predictions are negative, but maybe this is unavoidable in tree-bosting regression models (i.e. https://github.com/dmlc/xgboost/issues/1581)

Thank you so much in advance.

catboost version: {0.11.2}

**Comment by annaveronika** [comment]
This is definitely an open question rather than an issue in catboost, so I would suggest to make a stackoverflow question for that - you will surely get a lot of advices!
As for an initial advice - you need to experiment, and try both - regression on all data and classification and regression for positive examples. You should also try using weights for both, classification and regression in case if you do it for all the data. But I don't know in advance if they will help.
Try all the ideas, and select what works best.
About best practices and parameters to tune - we have a block in documentation that explain them:
https://tech.yandex.com/catboost/doc/dg/concepts/parameter-tuning-docpage/

**Comment by annaveronika** [comment]
@gitmario Are you ok with closing this issue? I think it's rather an open question than an issue for catboost.

**Comment by gitmario** [comment]
Ok! I'll move it to Stack Overflow. Meanwhile, thanks for the reply
