### ISSUE TITLE
specifying one gpu_id is invalid in R?

### ISSUE THREAD

**Issue by joegaotao** [catboost/catboost#704]
I installed the latest release R-linux package v0.12.2, and run the demo code on GPU. But I found I couldn't set parameter 'devices' to one specified device, and all GPU were always used.

```
library(catboost)
train_pool_path <- system.file("extdata", "adult_train.1000", package = "catboost")
test_pool_path <- system.file("extdata", "adult_test.1000", package = "catboost")
cd_path <- system.file("extdata", "adult.cd", package = "catboost")
train_pool <- catboost.load_pool(train_pool_path, column_description = cd_path)
test_pool <- catboost.load_pool(test_pool_path, column_description = cd_path)
fit_params <- list(
  iterations = 100,
  thread_count = 10,
  loss_function = 'Logloss',
  ignored_features = c(4, 9),
  border_count = 32,
  depth = 5,
  learning_rate = 0.03,
  l2_leaf_reg = 3.5, task_type = "GPU", devices = "0")
model <- catboost.train(train_pool, test_pool, fit_params)
```

**Comment by Noxoomo** [comment]
Hi!
Will look for it.
Could you run with logging_level="Debug" for one iteration and attach stdout log?
And did CatBoost uses GPU for computations (nvidia-smi will show >0% of GPU usage) or it just uses some memory? In the second case it's caused by Nvidia driver, we currently check all available devices before learning, so some memory is used by NVIDIA driver per each devices.

And fast solution for you problem:  run your R script/session with env variable CUDA_VISIBLE_DEVICES=0 (and CatBoost will see just one device)

**Comment by joegaotao** [comment]
@Noxoomo You're correct. I carefully watched the GPU-Util, and only the device-0 has GPU usage, others just are invoke without any usage. setting env variable CUDA_VISIBLE_DEVICES=0 also can solve the problem. However, the data is so small, but I find the GPU-usage is close to 10Gb？
![screenshot from 2019-02-28 18-04-42](https://user-images.githubusercontent.com/451945/53558731-92bb1700-3b83-11e9-9b85-18da02cd593d.png)

**Comment by Noxoomo** [comment]
CatBoost allocates almost all GPU memory on start, because using standard Cuda allocator is expensive

You could control amount of memory, that catboost uses with gpu_ram_part option (fraction of GPU memory that catboost will use)
