### ISSUE TITLE
Backtracking type AnyImprovement only active when Leaf Iterations > 1

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#727]
The default for `--leaf-estimation-backtracking` is AnyImprovement. But the there's a test on line #523 of approx_calcer.cpp 

    const bool isTrivialWalker = gradientIterations == 1 || ctx->Params.ObliviousTreeOptions->LeavesEstimationBacktrackingType == ELeavesEstimationStepBacktracking::No;
 
`GradientWalker(...)` always only performs a single newton step if `isTrivialWalker==true`

What this means is the `AnyImprovement` code only ever runs if gradientIterations (`--leaf-estimation-iterations`) is >1 which isn't the default.

Not sure if this is intentional and the documentation isn't clear, or an error. 

Also as I've already raised, it's not possible to set gradientIterations > 1 for some loss functions, i.e. Quantile or MAE, so in these cases the default can never have any impact.

**Comment by annaveronika** [comment]
When you set n steps of backtracking, the steps are calculated as follows: each step is aether an addition or it's a scaling of the leaf value. Scaling is also a step, it counts as part of n steps.
If we would do otherwise, we would not know in advance, how much computation we will have to do on this step, and we might end up doing a lot of computation for 100 small steps, which we don't want to do.

This means that backtracking with 1 step will not do anything, that's why it's active when there is more than 1 step.

Thanks for the issue, we'll improve description in the docs!
