### ISSUE TITLE
Can't build from source with GPU Support (Linux)

### ISSUE THREAD

**Issue by lucidyan** [catboost/catboost#787]
I wanted to add Catboost GPU version to my nvidia-docker and follow your instructions.

So I clone repository and execute that:
```bash
cd catboost/python-package/catboost && \ 
python3 ../../../ya make -r -DUSE_ARCADIA_PYTHON=no  \ 
-DUSE_SYSTEM_PYTHON=3.5 \ 
-DCUDA_ROOT=/usr/local/cuda \ 
-DHAVE_CUDA=yes
``` 

`/usr/bin/env: ‘python’: No such file or directory`
At first, I faced with problem that you hardcode python interpreter path in the 'ya' file:
https://github.com/catboost/catboost/commit/a4206ec0d0506420181735978d79e293431aa1ab#diff-d74600e380dbf727f67113fd71669d88L1
In my case, I use python3 interpreter and don't have python installed at all, so I need to symlink (bad practice) it or run from python3 that you don't point in your manual. 
Also you don't provide information about how to install libc6-dev at all. 
It also says that `python2.7 python2.7-dev` packages is needed, which is not true.

`(CUDA HOST TOOLCHAIN-sbr:133831678) ERROR: '133831678'`
After that my builds fails with strange error `133831678` that doesn't make sense at all, before I search in the repository and found that I fall into the wrong IF in the cuda makefile. So it seems that your simply forgot mention `-DUSE_ARCADIA_PYTHON=no` flag into your manual.
https://github.com/catboost/catboost/commit/c914dde7d52b4e959bdddd4038b3cce6ba6ba303#diff-6c0adb63949a2f633db5a044ec0a0ce8L19
So it will be nice if you add to the docs what each parameter means and examples, especially for `-DPYTHON` flags that no make sense a lot.

Then I successfully build library (several minutes with all CPU-threads SIC!) and add this to the PYTHONPATH (in XGBoost/LightGBM packages it installed simply with setup.py).

And after all that I got that nice error:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/src/catboost/catboost/python-package/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostError, cv, train, sum_models  # noqa
  File "/usr/local/src/catboost/catboost/python-package/catboost/core.py", line 53, in <module>
    _catboost = get_catboost_bin_module()
  File "/usr/local/src/catboost/catboost/python-package/catboost/core.py", line 49, in get_catboost_bin_module
    import _catboost
ImportError: No module named '_catboost'
```
which seems so similar to, but it helps not at all
https://github.com/catboost/catboost/issues/10
https://github.com/catboost/catboost/issues/319
https://github.com/catboost/catboost/issues/381

So after all other packages like XGBoost, LightGBM, Tensorflow and others, installing CatBoost is truly painful. I attached my **Dockerfile** for reproducibility so you can share my pain too.

**Steps to reproduce:**
-  Download [Dockerfile.txt](https://github.com/catboost/catboost/files/3076856/Dockerfile.txt) and remove it extension 
- run `docker build -t "lucidyan/catboost-test" .`
- run `nvidia-docker run lucidyan/catboost-test:latest python3 -c 'import catboost'`

**catboost version**: https://github.com/catboost/catboost/commit/1c621990595e3afc6106ef91400e5f743cd525d8
Operating System: Ubuntu 16.04.5 LTS (nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 Docker Image)
**CUDA (System)**: Cuda compilation tools, release 9.0, V9.0.176; Driver Version: 390.116; 
**CPU**: Intel I7-7700
**GPU**: NVIDIA-1080TI

**Comment by david-waterworth** [comment]
Not 100% sure, I just use pip to install catboost in a docker

When I am building the python package, I use pyenv/virtualenv. I use the command below, with the pyenv activated (i.e. so python in this case runs python-3.7.1).

 ../../../ya make -r -DOS_SDK=local -DCUDA_ROOT=/usr/local/cuda -DHAVE_CUDA=yes

This seems to work ok on my real machine (Ubuntu 18.04), it doesn't seem to work in your dockerfile though

**Comment by david-waterworth** [comment]
After numerous false starts, I got this working

```
# Catboost
RUN cd /usr/local/src && \ 
    git clone https://github.com/catboost/catboost.git && \ 
    cd catboost && git checkout 1c621990595e3afc6106ef91400e5f743cd525d8 

RUN cd /usr/local/src/catboost/catboost/python-package/catboost && \ 
    python3 ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/usr/bin/python3.5-config

RUN cd /usr/local/src/catboost/catboost/python-package && \ 
    pip3 install -e .
```

Note: I didn't include the CUDA flags, but I think it'll still work with them. The _catboost error is caused (I believe) by building with the wrong version of python (which I assume happens if you don't pass the correct options to ya make). Using the  `-DPYTHON_CONFIG=/usr/bin/python3.5-config` fixes that.

Also note - you can just install using pip, i.e. `pip3 install catboost==0.13.1`, I like to do this using a requirements.txt file, I put all my python requirements in it and then copy to the container and install using `pip install -r requirements.txt`

**Comment by david-waterworth** [comment]
I made several attempts at this and I have the same issue as you - the python import fails, it's because it's failing to load the _catboost.so and I think this is because it's building it for python2 not python3

I think the build command should be

`../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/usr/bin/python3.5-config`

The docs do mention the config file should be `python3-config` and I tried renaming but it didn't help. 

Do you really need to build from source, have you tried just installing using pip? That's how I've been installing catboost in docker (I used `nvidia/cuda:10.0-base-ubuntu18.04`)

i.e.

`pip3 install catboost==0.13.1`

**Comment by lucidyan** [comment]
@ david-waterworth I have no problem building packages like LightGBM and XGBoost, so maximum performance and errors are excluded.
For example, with CatBoost, for YetiRankPairwise objective my interpreter dies (on several machines). Is it my mistake, the wrong build or the error in the code? I don't know.

In addition, I would like the documentation to be relevant. And in 2019, python2 was not used by default.

**Comment by david-waterworth** [comment]
@lucidyan yes I have similar problems when I build using system python 3.6 then run in a 3.7 virtual env - it seg faults

I got this to work in your container (no GPU support)

`/usr/bin/python3.5 /usr/local/src/catboost/ya make /usr/local/src/catboost/catboost/python-package/catboost --no-src-links -r --output /usr/local/src/catboost/ -DPYTHON_BIN=/usr/bin/python3.5 -DPYTHON_CONFIG=/usr/bin/python3.5-config -DNO_DEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DHAVE_CUDA=no
`

But when I try

`/usr/bin/python3.5 /usr/local/src/catboost/ya make /usr/local/src/catboost/catboost/python-package/catboost --no-src-links -r --output /usr/local/src/catboost/ -DPYTHON_BIN=/usr/bin/python3.5 -DPYTHON_CONFIG=/usr/bin/python3.5-config -DNO_DEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DHAVE_CUDA=yes -DCUDA_ROOT=/usr/local/cuda
`

I get

------- PREPARE $(CUDA_HOST_TOOLCHAIN-sbr:133831678)
ERROR: '133831678'
Failed

I don't think it's using python2, you just need to make sure that you pass in `-DPYTHON_BIN=/usr/bin/python3.5` and ` -DPYTHON_CONFIG=/usr/bin/python3.5-config` so it can find the python exe, and the script which returns the libs / includes etc.

**Comment by kizill** [comment]
I guess this issue is too old and i'm not sure whether it's useful for now :)
But i'd like to write a possibly useful key on how to look at super actual build-for-*Nix instructions:
https://github.com/catboost/catboost/blob/master/ci/build_all_nix.sh
We run this script on MacOS and Linux in CI&CD system on each commit, just setup proper  `CUDA_ARG` and `JAVA_HOME` env variables, for example `CUDA_ARG=-DHAVE_CUDA=yes -DCUDA_ROOT=/usr/local/cuda-11.0/` and `JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/` (that's how our linux binaries are built)
