### ISSUE TITLE
error: 'allocations[0]' may be used uninitialized in this function

### ISSUE THREAD

**Issue by david-waterworth** [catboost/catboost#800]
When I build with the following flags

-DUSE_ARCADIA_CUDA=no -DUSE_ARCADIA_CUDA_HOST_COMPILER=no

I get series of warnings:

/home/david/dev/catboost/contrib/libs/cub/cub/device/dispatch/../../agent/single_pass_scan_operators.cuh:323:7: error: 'allocations[0]' may be used uninitialized in this function [-Werror=maybe-uninitialized]

If I set 

-DUSE_ARCADIA_CUDA=no -DUSE_ARCADIA_CUDA_HOST_COMPILER=yes

It builds fine. The issue seems to be that -Werror is set, but I just wanted to verify what the USE_ARCADIA_CUDA_HOST_COMPILER flag actually does. The comments in ya.make imply USE_ARCADIA_CUDA_HOST_COMPILER=yes means download and use clang 4.0 (I have 6.0 installed so I'm assuming clang now treats this as a warning and didn't in 4.0?)

IF (USE_ARCADIA_CUDA_HOST_COMPILER)
    IF (HOST_OS_LINUX AND HOST_ARCH_X86_64)
        IF (OS_LINUX AND ARCH_X86_64)
            IF (CUDA_VERSION STREQUAL "10.0")
                DECLARE_EXTERNAL_RESOURCE(CUDA_HOST_TOOLCHAIN sbr:243907179) # Clang 4.0 for Linux x86-64 (not latest)

**Comment by ljluestc** [comment]
If you prefer to have the build process treat those warnings as errors and fail the build, you can modify the build flags to include` -Wno-error=maybe-uninitialized.`

**Comment by andrey-khropov** [comment]
It has been fixed in CUB in https://github.com/NVIDIA/cub/commit/5eea3c65eab08324f45c709bbfb9a1de85b1ae93#diff-f214df404d27253685251d76554b147a5324e0d1d0c993c34b5238b10f41830c and updated in CatBoost contrib in https://github.com/catboost/catboost/commit/1a224afb0403cd7a3b2e4c2aaf343f50f3e5051f#diff-306e5bbbaa64e15ba77a22f0fcb05de9abd050ca98eaa734b4a2e63fc4164cb3
