### ISSUE TITLE
get_all_params()

### ISSUE THREAD

**Issue by annaveronika** [catboost/catboost#833]
Returns all params that were set in training. As opposed to get_params() that returns only the ones specified by a user.

**Comment by annaveronika** [comment]
This is a highly requested feature, we will be happy to get help here! We'll explain how to add it.

**Comment by awant** [comment]
I found _get_params method:
https://github.com/catboost/catboost/blob/93b614062392aa7b8300c008df3375a8e3dbef54/catboost/python-package/catboost/core.py#L1003
What else should be added?

**Comment by david-waterworth** [comment]
I'm not sure if I understand this correctly, but get_params() really should return all parameters, user set or not. This is how the standard sklearn implementation behaves.

The issue is I'm reading a json file which contains pipeline parameters some of which aren't part of my cross-validation pipeline (i.e. they include parameters used to load the training data). What I would like to do is call get_params() on my pipeline, remove anything which isn't a pipeline parameter, then call set_params().

This fails since catboost get_params() doesn't return it's parameters unless they've already been changed from their defaults so it doesn't really conform with the sklearn interface in my opinion. get_all_params() doesn't really fix this as it should be the behavior expected from get_params()?

**Comment by annaveronika** [comment]
get_params returns parameters that are set by the user, get_all_params() returns all parameters.
We cannot return parameters that have not been set during construction of the estimator, because it will be incompatable with sklearn rules - sklearn requires that all params are set in initialization of the estimator. Plus it will be a whole lot of parameters, which not everyone wants to read.

So please use both functions. The second one (get_all_params) will be on pypi this week, and it's already in code, so if you want it now, you can build from source.

**Comment by david-waterworth** [comment]
The problem is when you call set_params() on a sklearn pipeline which contains a catboost step it calls get_params() in order to validate that the parameters you’ve passed are in fact valid.

So it fails in certain cross validation cases where you don’t pre-initialise all the parameter via the constructor - ie when searching a complex hyper-parameter space using hyperopt.

**Comment by buhrmann** [comment]
Just to add that I think @david-waterworth is right. The current implementation of catboost's `get_params` is incompatible with sklearn, and so catboost cannot be used correctly in sklearn's Pipeline e.g. The relevant section in the docs is this: https://scikit-learn.org/stable/developers/develop.html#get-params-and-set-params. Specifically, `get_params` should return a "dict of the` __init__` parameters of the estimator, together with their values", i.e. _all_ parameters defined in the constructor, not just those passed in by the user explicitly. `get_all_params` doesn't help since sklearn only knows about and calls `get_params` internally.
