### ISSUE TITLE
What is AUC (eval_metric) measuring when CatBoost is performing 3-class ranking

### ISSUE THREAD

**Issue by hrbzkm98** [catboost/catboost#942]
Problem: 
The problem at hand is to predict target variable (3 classes, with 0 < 1 < 2 ordering) using ranking. The eval_metric parameter is set to AUC, the loss is set to PairLogit. clf.predict() produces a N by 1 vector of numerical values rather than N by 3 matrix of probabilities. In this case, what is AUC measuring? How is AUC calculated?

catboost version: v0.15
Operating System: Linux

**Comment by annaveronika** [comment]
If I remember correctly, we have temporary forbidden to use AUC for multiclass several versions ago.
Initially it was AUC one-vs-all, but since it might be misleading, for example give value less than 1 for perfect classification, we have decided to disable it.

We are now adding new AUC metric for multiclass (AUC Mu), which doesn't have this problem. In our next release we'll provide AUC for multiclass, which is AUC Mu by default, and can be one-vs-all if you set this as a type for AUC.

Here is the paper, describing both options:
http://proceedings.mlr.press/v97/kleiman19a/kleiman19a.pdf

**Comment by hrbzkm98** [comment]
OK, but when I used CatBoost class for ranking using loss function QuerySoftmax/PairLogit, the output of the predict function is a one dimensional vector, rather than a multi class prediction with discrete classes 0, 1, or 2. I get in this case AUC doesn’t make sense to calculate. But what exactly is the metric Accuracy calculating? The accuracy I got is 0.7. Is this calculating mean squared error? If it is purely measuring class accuracy it should get a score of 0.

**Comment by annaveronika** [comment]
AUC for ranking is regular AUC, which is the portion of correctly ordered pairs of samples.
And Accuracy metric is described here:
https://catboost.ai/docs/concepts/loss-functions-classification.html

**Comment by hrbzkm98** [comment]
Not sure what the definition of Accuracy is when it comes to the prediction being continuous while target being discrete. Is CatBoost doing anything behind the scenes? How do you define TP and TN? Thanks for clearing up the definition of AUC!

**Comment by annaveronika** [comment]
Currently we use threshold 0.5 on prediction to decide if sample is classified as a positive.
We plan to add parameter proba_threshold for classification metrics to make it possible to look on results with different thresholds.

**Comment by hrbzkm98** [comment]
Thank you so much Anna! We can close this issue.
