### ISSUE TITLE
How to avoid creating the pool object and train the model

### ISSUE THREAD

**Issue by anuragreddygv323** [catboost/catboost#949]
Problem: Is there a way to avoid the creation of the pool object which takes up memory because the dataset is huge and only after creating the pool object can I delete the train, test data. Is there a way I can just load train and test data in memory and do the training

@annaveronika

**Comment by andrey-khropov** [comment]
What kind of API are you interested in (CLI, python, R) ?

If we're talking about python API there're optimized cases when original feature data is not copied to Pool object internal storage but stored as references to existing python data. Right now this is possible for numerical data that is stored in [column-major order](https://docs.scipy.org/doc/numpy/glossary.html#term-column-major) (either as numpy.ndarray created with specified ``order='F'`` or as pandas.DataFrame columns) and has dtype=numpy.float32 (because that is what CatBoost needs internally). It is planned to expand this zero-copy optimization to other common data types very soon (in two weeks timeframe).

When using CLI API data is also not duplicated but loaded into internal pool objects directly from files, so there's no extra RAM overhead.
Dataset file format supported by CatBoost is described here - https://catboost.ai/docs/concepts/input-data_values-file.html.

**Comment by annaveronika** [comment]
Actually you can create Pool from files in Python also.

**Comment by annaveronika** [comment]
I hope it helped. Let us know if you have more questions.
